[build]
  command = "npm run build"
  publish = "build"
[[plugins]]
  package = "netlify-plugin-cloudinary"
  [plugins.inputs]
  cloudName = "daya2ittg"
  [[plugins]]
  package = "netlify-plugin-image-optim"